--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 31/05/2023 12:12:34 pm
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE hospital;

--
-- Drop table `add_opdpatients`
--
DROP TABLE IF EXISTS add_opdpatients;

--
-- Drop table `admin`
--
DROP TABLE IF EXISTS admin;

--
-- Drop table `appointment`
--
DROP TABLE IF EXISTS appointment;

--
-- Drop table `billing`
--
DROP TABLE IF EXISTS billing;

--
-- Drop table `billing_records`
--
DROP TABLE IF EXISTS billing_records;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Drop table `doctor`
--
DROP TABLE IF EXISTS doctor;

--
-- Drop table `doctor_timings`
--
DROP TABLE IF EXISTS doctor_timings;

--
-- Drop table `medicine`
--
DROP TABLE IF EXISTS medicine;

--
-- Drop table `orders`
--
DROP TABLE IF EXISTS orders;

--
-- Drop table `patient`
--
DROP TABLE IF EXISTS patient;

--
-- Drop table `payment`
--
DROP TABLE IF EXISTS payment;

--
-- Drop table `prescription`
--
DROP TABLE IF EXISTS prescription;

--
-- Drop table `prescription_records`
--
DROP TABLE IF EXISTS prescription_records;

--
-- Drop table `room`
--
DROP TABLE IF EXISTS room;

--
-- Drop table `service_type`
--
DROP TABLE IF EXISTS service_type;

--
-- Drop table `tblautonumber`
--
DROP TABLE IF EXISTS tblautonumber;

--
-- Drop table `tbldepartment`
--
DROP TABLE IF EXISTS tbldepartment;

--
-- Drop table `tblemployee`
--
DROP TABLE IF EXISTS tblemployee;

--
-- Drop table `tbllogs`
--
DROP TABLE IF EXISTS tbllogs;

--
-- Drop table `tblposition`
--
DROP TABLE IF EXISTS tblposition;

--
-- Drop table `tbltimetable`
--
DROP TABLE IF EXISTS tbltimetable;

--
-- Drop table `tblverifytimeintimeout`
--
DROP TABLE IF EXISTS tblverifytimeintimeout;

--
-- Drop table `treatment`
--
DROP TABLE IF EXISTS treatment;

--
-- Drop table `treatment_records`
--
DROP TABLE IF EXISTS treatment_records;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `useraccounts`
--
DROP TABLE IF EXISTS useraccounts;

--
-- Set default database
--
USE hospital;

--
-- Create table `useraccounts`
--
CREATE TABLE useraccounts (
  ACCOUNT_ID int NOT NULL AUTO_INCREMENT,
  ACCOUNT_NAME varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  ACCOUNT_USERNAME varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  ACCOUNT_PASSWORD text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  ACCOUNT_TYPE varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  EMPID int NOT NULL,
  USERIMAGE varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (ACCOUNT_ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `user`
--
CREATE TABLE user (
  userid int NOT NULL AUTO_INCREMENT,
  loginname varchar(50) NOT NULL,
  password varchar(10) NOT NULL,
  patientname varchar(50) NOT NULL,
  mobileno varchar(15) NOT NULL,
  email varchar(50) NOT NULL,
  createddateandtime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `treatment_records`
--
CREATE TABLE treatment_records (
  treatment_records_id int NOT NULL AUTO_INCREMENT,
  treatmentid int NOT NULL,
  appointmentid int NOT NULL,
  patientid int NOT NULL,
  doctorid int NOT NULL,
  treatment_description text NOT NULL,
  uploads varchar(100) NOT NULL,
  treatment_date date NOT NULL,
  treatment_time time NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (treatment_records_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `treatment`
--
CREATE TABLE treatment (
  treatmentid int NOT NULL AUTO_INCREMENT,
  treatmenttype varchar(25) NOT NULL,
  treatment_cost decimal(10, 2) NOT NULL,
  note text NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (treatmentid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 22,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `tblverifytimeintimeout`
--
CREATE TABLE tblverifytimeintimeout (
  VerifyID int NOT NULL AUTO_INCREMENT,
  EmployeeID varchar(90) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  TimeIn varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  TimeOut varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  Verification varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  DateValidation date NOT NULL,
  PRIMARY KEY (VerifyID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `tbltimetable`
--
CREATE TABLE tbltimetable (
  TimeTableID int NOT NULL AUTO_INCREMENT,
  EmployeeID varchar(90) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  TimeInAM varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  TimeOutAM varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  TimeInPM varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  TimeOutPM varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  AttendDate date NOT NULL,
  PRIMARY KEY (TimeTableID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 72,
AVG_ROW_LENGTH = 230,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `tblposition`
--
CREATE TABLE tblposition (
  PositionID int NOT NULL AUTO_INCREMENT,
  PositionCode varchar(30) NOT NULL,
  Description varchar(255) NOT NULL,
  DepartmentID int NOT NULL,
  PRIMARY KEY (PositionID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 4096,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `DepartmentID` on table `tblposition`
--
ALTER TABLE tblposition
ADD INDEX DepartmentID (DepartmentID);

--
-- Create table `tbllogs`
--
CREATE TABLE tbllogs (
  LOGID int NOT NULL AUTO_INCREMENT,
  USERID int NOT NULL,
  LOGDATETIME datetime NOT NULL,
  LOGROLE varchar(30) NOT NULL,
  LOGMODE varchar(30) NOT NULL,
  PRIMARY KEY (LOGID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 202,
AVG_ROW_LENGTH = 442,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `tblemployee`
--
CREATE TABLE tblemployee (
  ID int NOT NULL AUTO_INCREMENT,
  EmployeeID varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  Firstname varchar(99) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  Lastname varchar(99) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  Middlename varchar(99) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  Address varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  Gender varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  BirthDate date NOT NULL,
  Age int NOT NULL,
  ContactNo varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  EmployeeStatus varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PositionID int NOT NULL,
  EmPhoto varchar(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  Cand_Status varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `tbldepartment`
--
CREATE TABLE tbldepartment (
  DepartmentID int NOT NULL AUTO_INCREMENT,
  Department varchar(30) NOT NULL,
  Description varchar(99) NOT NULL,
  PRIMARY KEY (DepartmentID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `tblautonumber`
--
CREATE TABLE tblautonumber (
  AutoID int NOT NULL AUTO_INCREMENT,
  AutoStart varchar(30) NOT NULL,
  AutoEnd int NOT NULL,
  AutoInc int NOT NULL,
  AutoType varchar(30) NOT NULL,
  PRIMARY KEY (AutoID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `service_type`
--
CREATE TABLE service_type (
  service_type_id int NOT NULL AUTO_INCREMENT,
  service_type varchar(100) NOT NULL,
  servicecharge float(10, 2) NOT NULL,
  description text NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (service_type_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 15,
AVG_ROW_LENGTH = 3276,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `room`
--
CREATE TABLE room (
  roomid int NOT NULL AUTO_INCREMENT,
  roomtype varchar(25) NOT NULL,
  roomno int NOT NULL,
  noofbeds int NOT NULL,
  room_tariff float(10, 2) NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (roomid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 20,
AVG_ROW_LENGTH = 3276,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `prescription_records`
--
CREATE TABLE prescription_records (
  prescription_record_id int NOT NULL AUTO_INCREMENT,
  prescription_id int NOT NULL,
  medicine_name varchar(25) NOT NULL,
  cost float(10, 2) NOT NULL,
  unit int NOT NULL,
  dosage varchar(25) NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (prescription_record_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `prescription`
--
CREATE TABLE prescription (
  prescriptionid int NOT NULL AUTO_INCREMENT,
  treatment_records_id int NOT NULL,
  doctorid int NOT NULL,
  patientid int NOT NULL,
  delivery_type varchar(10) NOT NULL COMMENT 'Delivered through appointment or online order',
  delivery_id int NOT NULL COMMENT 'appointmentid or orderid',
  prescriptiondate date NOT NULL,
  status varchar(10) NOT NULL,
  appointmentid int NOT NULL,
  PRIMARY KEY (prescriptionid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2048,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `payment`
--
CREATE TABLE payment (
  paymentid int NOT NULL AUTO_INCREMENT,
  patientid int NOT NULL,
  appointmentid int NOT NULL,
  paiddate date NOT NULL,
  paidtime time NOT NULL,
  paidamount float(10, 2) NOT NULL,
  status varchar(10) NOT NULL,
  cardholder varchar(50) NOT NULL,
  cardnumber int NOT NULL,
  cvvno int NOT NULL,
  expdate date NOT NULL,
  PRIMARY KEY (paymentid)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `patient`
--
CREATE TABLE patient (
  patientid int NOT NULL AUTO_INCREMENT,
  patientname varchar(50) NOT NULL,
  admissiondate date NOT NULL,
  admissiontime time NOT NULL,
  address varchar(250) DEFAULT NULL,
  mobileno varchar(15) DEFAULT NULL,
  city varchar(25) DEFAULT NULL,
  pincode varchar(20) DEFAULT NULL,
  loginid varchar(50) DEFAULT NULL,
  password varchar(25) DEFAULT NULL,
  bloodgroup varchar(20) DEFAULT NULL,
  gender varchar(10) DEFAULT NULL,
  dob date DEFAULT NULL,
  status varchar(10) DEFAULT NULL,
  PRIMARY KEY (patientid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `loginid` on table `patient`
--
ALTER TABLE patient
ADD INDEX loginid (loginid);

--
-- Create table `orders`
--
CREATE TABLE orders (
  orderid int NOT NULL AUTO_INCREMENT,
  patientid int NOT NULL,
  doctorid int NOT NULL,
  prescriptionid int NOT NULL,
  orderdate date NOT NULL,
  deliverydate date NOT NULL,
  address text NOT NULL,
  mobileno varchar(15) NOT NULL,
  note text NOT NULL,
  status varchar(10) NOT NULL,
  payment_type varchar(20) NOT NULL,
  card_no varchar(20) NOT NULL,
  cvv_no varchar(5) NOT NULL,
  expdate date NOT NULL,
  card_holder varchar(50) NOT NULL,
  PRIMARY KEY (orderid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 56,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `medicine`
--
CREATE TABLE medicine (
  medicineid int NOT NULL AUTO_INCREMENT,
  medicinename varchar(25) NOT NULL,
  medicinecost float(10, 2) NOT NULL,
  description text NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (medicineid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `doctor_timings`
--
CREATE TABLE doctor_timings (
  doctor_timings_id int NOT NULL AUTO_INCREMENT,
  doctorid int NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  available_day varchar(15) NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (doctor_timings_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `doctor`
--
CREATE TABLE doctor (
  doctorid int NOT NULL AUTO_INCREMENT,
  doctorname varchar(50) NOT NULL,
  mobileno varchar(15) NOT NULL,
  departmentid int NOT NULL,
  loginid varchar(25) NOT NULL,
  password varchar(25) NOT NULL,
  status varchar(10) NOT NULL,
  education varchar(25) NOT NULL,
  experience float(11, 1) NOT NULL,
  consultancy_charge float(10, 2) NOT NULL,
  PRIMARY KEY (doctorid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `department`
--
CREATE TABLE department (
  departmentid int NOT NULL AUTO_INCREMENT,
  departmentname varchar(100) NOT NULL,
  description text NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (departmentid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `billing_records`
--
CREATE TABLE billing_records (
  billingservice_id int NOT NULL AUTO_INCREMENT,
  billingid int NOT NULL,
  bill_type_id int NOT NULL COMMENT 'id of service charge or treatment charge',
  bill_type varchar(250) NOT NULL,
  bill_amount float(10, 2) NOT NULL,
  bill_date date NOT NULL,
  status varchar(10) NOT NULL,
  PRIMARY KEY (billingservice_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 13,
AVG_ROW_LENGTH = 1820,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `billing`
--
CREATE TABLE billing (
  billingid int NOT NULL AUTO_INCREMENT,
  patientid int NOT NULL,
  appointmentid int NOT NULL,
  billingdate date NOT NULL,
  billingtime time NOT NULL,
  discount float(10, 2) NOT NULL,
  taxamount float(10, 2) NOT NULL,
  discountreason text NOT NULL,
  discharge_time time NOT NULL,
  discharge_date date NOT NULL,
  PRIMARY KEY (billingid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `appointment`
--
CREATE TABLE appointment (
  appointmentid int NOT NULL AUTO_INCREMENT,
  appointmenttype varchar(25) DEFAULT NULL,
  patientid int DEFAULT NULL,
  roomid int DEFAULT NULL,
  departmentid int DEFAULT NULL,
  appointmentdate date DEFAULT NULL,
  appointmenttime time DEFAULT NULL,
  doctorid int DEFAULT NULL,
  status varchar(10) DEFAULT NULL,
  app_reason text DEFAULT NULL,
  PRIMARY KEY (appointmentid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `admin`
--
CREATE TABLE admin (
  adminid int NOT NULL AUTO_INCREMENT,
  adminname varchar(25) NOT NULL,
  loginid varchar(25) NOT NULL,
  password varchar(25) NOT NULL,
  status varchar(10) NOT NULL,
  usertype varchar(30) NOT NULL,
  PRIMARY KEY (adminid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `adminname` on table `admin`
--
ALTER TABLE admin
ADD UNIQUE INDEX adminname (adminname);

--
-- Create table `add_opdpatients`
--
CREATE TABLE add_opdpatients (
  id int NOT NULL,
  a_fname varchar(255) NOT NULL,
  a_gender varchar(255) NOT NULL,
  a_age int NOT NULL,
  a_complaint text NOT NULL,
  a_historypresentillness text NOT NULL,
  a_bp varchar(255) NOT NULL,
  a_rr varchar(255) NOT NULL,
  a_cr varchar(255) NOT NULL,
  a_temp varchar(255) NOT NULL,
  a_wt varchar(255) NOT NULL,
  a_pr varchar(255) NOT NULL,
  a_physicalexam text NOT NULL,
  a_diagnosis text NOT NULL,
  a_medication text NOT NULL,
  a_physician_id int NOT NULL,
  a_date date NOT NULL,
  log_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status int NOT NULL
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table useraccounts
--
INSERT INTO useraccounts VALUES
(1, 'Marianne Joyce Alejaga', 'admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 'Administrator', 1234, 'photos/import2.png'),
(2, 'Dr. Aura Bree Dayo - Lacdao', 'dayo', '241aa33f629fbd977e478ce7b884a29814d06e11', 'Doctor', 0, ''),
(3, 'Dr. Aikee Marvin Lacdao', 'lacdao', 'ffb222bdffc875fb24eee3cf19f35c892b580422', 'Doctor', 0, ''),
(4, 'Dr. Mark Christian Agase', 'agase', '574676bc37bf08f74e15ff61f0e9b781215f5f9b', 'Doctor', 0, ''),
(5, 'Dr. Jerry Mae Blasurca', 'blasurca', '792bd51503a251804d7394131aaa7e62ae1f878b', 'Doctor', 0, ''),
(6, 'Dr. Jefrrey De Tomas', 'tomas', '2bc6038c3dfca09b2da23c8b6da8ba884dc2dcc2', 'Doctor', 0, ''),
(7, 'Dr. Gessele S. Cabilitasan', 'cabilitasan', 'ac7bdd94d25ff7c0eeac1ca4085973ef8ee2d530', 'Doctor', 0, ''),
(8, 'Dr. Eric D. Aguro', 'aguro', 'd83981141fd82f21dec5f836c563ea81f61be657', 'Doctor', 0, '');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'user', 'admin', 'Nezuko', '', '', '2022-02-09 11:21:45');

-- 
-- Dumping data for table treatment_records
--
INSERT INTO treatment_records VALUES
(1, 20, 1, 1, 1, 'Test your Blood', '1015614602', '2022-11-15', '22:03:00', 'Active'),
(2, 20, 2, 2, 1, 'test your blood', '387889831', '2022-11-16', '12:54:00', 'Active');

-- 
-- Dumping data for table treatment
--
INSERT INTO treatment VALUES
(20, 'Blood test', 300.00, 'total IgE', 'Active'),
(21, 'X Ray', 200.00, 'X Ray @200', 'Active');

-- 
-- Dumping data for table tblverifytimeintimeout
--
INSERT INTO tblverifytimeintimeout VALUES
(1, '0010266936', '11:13 PM', '11:13 PM', 'TimeIn', '2022-10-11'),
(2, '0689248870', '10:44 AM', '10:44 AM', 'TimeIn', '2022-11-29'),
(3, '0692453478', '10:40 PM', '10:40 PM', 'TimeIn', '2022-12-09'),
(4, '0692214614', '01:39 PM', '01:39 PM', 'TimeIn', '2022-11-16'),
(5, '0686025460', '01:01 PM', '01:01 PM', 'TimeIn', '2022-11-16'),
(6, '0692043622', '01:01 PM', '01:01 PM', 'TimeIn', '2022-11-16'),
(7, '0690975846', '01:01 PM', '01:01 PM', 'TimeIn', '2022-11-16'),
(8, '0693928822', '01:02 PM', '01:02 PM', 'TimeIn', '2022-11-16'),
(9, '0691936358', '01:02 PM', '01:02 PM', 'TimeIn', '2022-11-16'),
(10, '0698423142', '01:02 PM', '01:02 PM', 'TimeIn', '2022-11-16'),
(11, '0696768102', '01:02 PM', '01:02 PM', 'TimeIn', '2022-11-16');

-- 
-- Dumping data for table tbltimetable
--
INSERT INTO tbltimetable VALUES
(1, '0692453478', '', '', '12:39 PM', '12:39 PM', '2022-09-09'),
(2, '0692453478', '', '', '12:49 PM', '12:49 PM', '2022-09-15'),
(3, '0692214614', '', '', '12:57 PM', '12:57 PM', '2022-09-15'),
(4, '0689248870', '', '', '01:44 PM', '01:53 PM', '2022-09-15'),
(5, '0692453478', '', '', '01:43 PM', '01:43 PM', '2022-09-26'),
(6, '0692453478', '', '', '01:19 PM', '01:19 PM', '2022-09-27'),
(7, '0692214614', '', '', '01:21 PM', '01:21 PM', '2022-09-27'),
(8, '0689248870', '', '', '01:24 PM', '01:25 PM', '2022-09-27'),
(9, '0010266936', '', '', '01:26 PM', '01:27 PM', '2022-09-27'),
(10, '0692453478', '', '', '08:40 PM', '08:40 PM', '2022-09-28'),
(11, '0689248870', '', '', '08:41 PM', '08:41 PM', '2022-09-28'),
(12, '0692214614', '', '', '08:59 PM', '', '2022-09-28'),
(13, '0010266936', '', '', '09:03 PM', '', '2022-09-28'),
(14, '0692453478', '', '', '10:49 PM', '10:53 PM', '2022-10-01'),
(15, '0689248870', '', '', '10:55 PM', '10:56 PM', '2022-10-01'),
(16, '0692214614', '', '', '10:59 PM', '11:00 PM', '2022-10-01'),
(17, '0689248870', '', '', '09:23 PM', '09:24 PM', '2022-10-10'),
(18, '0692214614', '', '', '09:28 PM', '09:29 PM', '2022-10-10'),
(19, '0692453478', '', '', '09:34 PM', '09:34 PM', '2022-10-10'),
(20, '0010266936', '', '', '09:37 PM', '09:37 PM', '2022-10-10'),
(21, '0689248870', '', '', '10:07 PM', '10:08 PM', '2022-10-11'),
(22, '0692453478', '', '', '10:09 PM', '10:09 PM', '2022-10-11'),
(23, '0692214614', '', '', '10:14 PM', '10:14 PM', '2022-10-11'),
(24, '0010266936', '', '', '11:13 PM', '11:13 PM', '2022-10-11'),
(25, '0692453478', '', '', '10:09 PM', '10:10 PM', '2022-10-12'),
(26, '0692453478', '', '', '04:08 PM', '04:08 PM', '2022-11-03'),
(27, '0692453478', '', '', '10:31 PM', '10:44 PM', '2022-11-09'),
(28, '0686025460', '', '', '10:47 PM', '10:48 PM', '2022-11-09'),
(29, '0686025460', '', '', '10:47 PM', '10:48 PM', '2022-11-09'),
(30, '0686025460', '', '', '10:47 PM', '10:48 PM', '2022-11-09'),
(31, '0686025460', '', '', '10:47 PM', '10:48 PM', '2022-11-09'),
(32, '0686025460', '', '', '10:48 PM', '10:48 PM', '2022-11-09'),
(33, '0692043622', '', '', '10:49 PM', '10:49 PM', '2022-11-09'),
(34, '0692214614', '', '', '10:50 PM', '10:51 PM', '2022-11-09'),
(35, '0689248870', '', '', '10:52 PM', '10:53 PM', '2022-11-09'),
(36, '0692453478', '09:10 AM', '09:11 AM', '', '', '2022-11-10'),
(37, '0692453478', '09:11 AM', '09:11 AM', '', '', '2022-11-10'),
(38, '0689248870', '09:18 AM', '09:18 AM', '', '', '2022-11-10'),
(39, '0689248870', '09:18 AM', '09:18 AM', '', '', '2022-11-10'),
(40, '0692214614', '09:20 AM', '09:20 AM', '', '', '2022-11-10'),
(41, '0692214614', '09:20 AM', '09:20 AM', '', '', '2022-11-10'),
(42, '0686025460', '09:21 AM', '09:21 AM', '', '', '2022-11-10'),
(43, '0686025460', '09:21 AM', '09:21 AM', '', '', '2022-11-10'),
(44, '0692043622', '09:27 AM', '09:27 AM', '', '', '2022-11-10'),
(45, '0692043622', '09:27 AM', '09:27 AM', '', '', '2022-11-10'),
(46, '0689248870', '10:00 AM', '', '', '', '2022-11-10'),
(47, '0692453478', '10:05 AM', '', '', '', '2022-11-10'),
(48, '0692043622', '10:32 AM', '', '', '', '2022-11-10'),
(49, '0692453478', '11:26 AM', '11:27 AM', '06:35 PM', '06:33 PM', '2022-11-15'),
(50, '0692214614', '', '', '03:03 PM', '03:03 PM', '2022-11-15'),
(51, '0689248870', '', '', '06:33 PM', '06:37 PM', '2022-11-15'),
(52, '0686025460', '', '', '06:33 PM', '06:33 PM', '2022-11-15'),
(53, '0692043622', '', '', '06:33 PM', '06:33 PM', '2022-11-15'),
(54, '0690975846', '', '', '06:33 PM', '06:33 PM', '2022-11-15'),
(55, '0693928822', '', '', '06:33 PM', '06:34 PM', '2022-11-15'),
(56, '0691936358', '', '', '06:34 PM', '06:34 PM', '2022-11-15'),
(57, '0698423142', '', '', '06:34 PM', '06:34 PM', '2022-11-15'),
(58, '0696768102', '', '', '06:34 PM', '06:34 PM', '2022-11-15'),
(59, '0692453478', '', '', '01:01 PM', '01:01 PM', '2022-11-16'),
(60, '0692214614', '', '', '01:01 PM', '01:01 PM', '2022-11-16'),
(61, '0689248870', '', '', '01:01 PM', '01:01 PM', '2022-11-16'),
(62, '0686025460', '', '', '01:01 PM', '', '2022-11-16'),
(63, '0692043622', '', '', '01:01 PM', '', '2022-11-16'),
(64, '0690975846', '', '', '01:01 PM', '01:02 PM', '2022-11-16'),
(65, '0693928822', '', '', '01:02 PM', '01:02 PM', '2022-11-16'),
(66, '0691936358', '', '', '01:02 PM', '01:02 PM', '2022-11-16'),
(67, '0698423142', '', '', '01:02 PM', '01:02 PM', '2022-11-16'),
(68, '0696768102', '', '', '01:02 PM', '', '2022-11-16'),
(69, '0689248870', '10:44 AM', '10:44 AM', '', '', '2022-11-29'),
(70, '0689248870', '10:44 AM', '10:44 AM', '', '', '2022-11-29'),
(71, '0692453478', '', '', '10:40 PM', '10:40 PM', '2022-12-09');

-- 
-- Dumping data for table tblposition
--
INSERT INTO tblposition VALUES
(1, 'RN', 'NURSE', 1),
(2, 'NA', 'NURSING ATTENDANT / NURSING ASSISTANT / NURSING AIDE', 2),
(3, 'AIDE', 'ADMINISTRATIVE ASSISTANT / ADMINISTRATIVE AIDE', 3),
(4, 'UW', 'UTILITY WORKER', 4);

-- 
-- Dumping data for table tbllogs
--
INSERT INTO tbllogs VALUES
(1, 1, '2022-01-24 01:53:37', 'Administrator', 'Logged out'),
(2, 1, '2022-01-24 02:48:48', 'Administrator', 'Logged in'),
(161, 1, '2022-11-08 09:33:28', 'Administrator', 'Logged in'),
(162, 1, '2022-11-08 09:33:47', 'Administrator', 'Logged out'),
(163, 1, '2022-11-08 09:33:52', 'Administrator', 'Logged in'),
(164, 1, '2022-11-08 10:19:29', 'Administrator', 'Logged out'),
(165, 8, '2022-11-08 10:19:40', 'Doctor', 'Logged in'),
(166, 1, '2022-11-08 12:45:32', 'Administrator', 'Logged in'),
(167, 1, '2022-11-08 15:19:29', 'Administrator', 'Logged in'),
(168, 1, '2022-11-09 12:18:28', 'Administrator', 'Logged in'),
(169, 1, '2022-11-09 13:01:11', 'Administrator', 'Logged out'),
(170, 1, '2022-11-09 13:01:15', 'Administrator', 'Logged in'),
(171, 1, '2022-11-09 15:31:29', 'Administrator', 'Logged in'),
(172, 1, '2022-11-10 02:08:19', 'Administrator', 'Logged in'),
(173, 1, '2022-11-12 05:59:20', 'Administrator', 'Logged in'),
(174, 1, '2022-11-14 10:58:44', 'Administrator', 'Logged in'),
(175, 1, '2022-11-15 04:26:30', 'Administrator', 'Logged in'),
(176, 1, '2022-11-15 08:02:54', 'Administrator', 'Logged in'),
(177, 1, '2022-11-15 08:03:05', 'Administrator', 'Logged out'),
(178, 1, '2022-11-15 08:03:12', 'Administrator', 'Logged in'),
(179, 1, '2022-11-15 08:04:20', 'Administrator', 'Logged out'),
(180, 1, '2022-11-15 11:23:36', 'Administrator', 'Logged in'),
(181, 1, '2022-11-15 11:32:16', 'Administrator', 'Logged in'),
(182, 1, '2022-11-15 11:38:54', 'Administrator', 'Logged out'),
(183, 1, '2022-11-15 11:41:07', 'Administrator', 'Logged in'),
(184, 1, '2022-11-15 11:41:35', 'Administrator', 'Logged out'),
(185, 1, '2022-11-15 11:43:45', 'Administrator', 'Logged in'),
(186, 1, '2022-11-15 15:55:49', 'Administrator', 'Logged in'),
(187, 1, '2022-11-16 06:00:09', 'Administrator', 'Logged in'),
(188, 1, '2022-11-16 06:38:38', 'Administrator', 'Logged in'),
(189, 1, '2022-11-19 14:25:12', 'Administrator', 'Logged in'),
(190, 1, '2022-11-22 14:30:58', 'Administrator', 'Logged in'),
(191, 1, '2022-11-29 03:44:15', 'Administrator', 'Logged in'),
(192, 1, '2022-12-07 02:47:21', 'Administrator', 'Logged in'),
(193, 1, '2022-12-07 03:09:06', 'Administrator', 'Logged out'),
(194, 1, '2022-12-09 15:37:42', 'Administrator', 'Logged in'),
(195, 1, '2023-01-15 14:59:53', 'Administrator', 'Logged in'),
(196, 1, '2023-05-30 18:44:24', 'Administrator', 'Logged in'),
(197, 1, '2023-05-30 18:44:31', 'Administrator', 'Logged out'),
(198, 1, '2023-05-30 18:45:52', 'Administrator', 'Logged in'),
(199, 1, '2023-05-30 18:45:55', 'Administrator', 'Logged out'),
(200, 1, '2023-05-30 18:45:55', 'Administrator', 'Logged in'),
(201, 1, '2023-05-31 03:29:05', 'Administrator', 'Logged in');

-- 
-- Dumping data for table tblemployee
--
INSERT INTO tblemployee VALUES
(1, '0692453478', 'JOANNA', 'ALEJAGA', 'J.', 'BRGY. BALUCUAN DAO, CAPIZ', 'Female', '1983-06-30', 39, '09300748152', 'Casual', 2, 'photo/joanna.jpg', 'Employee'),
(2, '0689248870', 'KEITH JULENE', 'BOLAÃ‘O', 'B.', 'POB. ILAYA DAO, CAPIZ', 'Female', '1998-10-07', 23, '09998086982', 'Casual', 1, 'photo/kitting.jpg', 'Employee'),
(3, '0692214614', 'YOLANDA', 'FERREN', 'F.', 'SAN JOSE DUMALAG, CAPIZ', 'Female', '1987-01-16', 35, '09469132087', 'Casual', 2, 'photo/dangdang.jpg', 'Employee'),
(4, '0686025460', 'ALDIE', 'MAGBANUA', 'F.', 'BRGY. DUYOC DAO, CAPIZ', 'Male', '1977-01-23', 45, '09484269410', 'Casual', 4, 'photo/aldie.jpg', 'Employee'),
(5, '0692043622', 'DINNAH', 'ARBIS', 'P.', 'BRGY. MANHOY DAO, CAPIZ', 'Female', '1980-08-13', 42, '09284727153', 'Casual', 1, 'photo/dynz.jpg', 'Employee'),
(6, '0690975846', 'MARY GRACE ', 'BUIZON', 'B.', 'POBLACION ILAWOD DAO, CAPIZ', 'Female', '1966-12-11', 55, '09496150953', 'Regular', 1, 'photo/buizon.jpg', ''),
(7, '0693928822', 'JOCYRIE', 'DEOCAMPO', 'D.', 'LACARON DAO, CAPIZ', 'Female', '1999-11-19', 22, '09267045440', 'Casual', 1, 'photo/jocyrie.jpg', ''),
(8, '0691936358', 'ERIKA JOY', 'MARCELINO', 'F. ', 'BRGY. MANGOSO SIGMA, CAPIZ', 'Female', '1995-01-28', 27, '09303532150', 'Casual', 2, 'photo/erika.jpg', ''),
(9, '0698423142', 'CAREN JANE', 'BEDIONES', 'J.', 'POBLACION NORTE SIGMA, CAPIZ', 'Female', '1991-10-21', 31, '09106213750', 'Casual', 1, '', ''),
(10, '0696768102', 'FRANCISCA', 'BIACO', 'F.', 'BGRY. CONSOLACION DUMALAG, CAPIZ', 'Female', '1986-10-03', 36, '09302828100', 'Casual', 1, '', '');

-- 
-- Dumping data for table tbldepartment
--
INSERT INTO tbldepartment VALUES
(1, 'MEDICINE', 'INTERNAL MEDICINE'),
(2, 'PHARMACY', 'REVIEWING MEDICATIONS'),
(3, 'LABORATORY', 'TECHNOLOGICAL RESEARCH'),
(4, 'RADIOLOGY', 'DIAGNOSTIC RADIOLOGY');

-- 
-- Dumping data for table tblautonumber
--
INSERT INTO tblautonumber VALUES
(1, '2017', 56, 1, 'AuthPrint');

-- 
-- Dumping data for table service_type
--
INSERT INTO service_type VALUES
(10, 'X-ray', 250.00, 'To take fractured photo copy', 'Active'),
(11, 'Scanning', 450.00, 'To scan body from injury', 'Active'),
(12, 'MRI', 300.00, 'Regarding body scan', 'Active'),
(13, 'Blood Testing', 150.00, 'To detect the type of disease', 'Active'),
(14, 'Diagnosis', 210.00, 'To analyse the diagnosis', 'Active');

-- 
-- Dumping data for table room
--
INSERT INTO room VALUES
(15, 'GENERAL WARD', 1, 20, 500.00, 'Active'),
(16, 'SPECIAL WARD', 2, 10, 100.00, 'Active'),
(17, 'GENERAL WARD', 2, 10, 500.00, 'Active'),
(18, 'GENERAL WARD', 121, 13, 150.00, 'Active'),
(19, 'GENERAL WARD', 850, 11, 500.00, 'Active');

-- 
-- Dumping data for table prescription_records
--
INSERT INTO prescription_records VALUES
(1, 1, '1', 3.00, 2, '0-1-1', 'Active'),
(2, 2, '2', 5.00, 3, '0-1-1', 'Active'),
(3, 3, '1', 3.00, 1, '1-1-1', 'Active'),
(4, 6, '1', 3.00, 1, '0-1-1 (Take a pill in the', 'Active'),
(5, 7, '2', 5.00, 1, '', 'Active');

-- 
-- Dumping data for table prescription
--
INSERT INTO prescription VALUES
(1, 0, 1, 1, '', 0, '2022-11-15', 'Active', 1),
(2, 0, 1, 2, '', 0, '2022-11-16', 'Active', 2),
(3, 0, 1, 2, '', 0, '2022-11-16', 'Active', 2),
(4, 0, 1, 2, '', 0, '2022-11-17', 'Active', 2),
(5, 0, 1, 2, '', 0, '2022-12-05', 'Active', 2),
(6, 0, 1, 2, '', 0, '0000-00-00', 'Active', 2),
(7, 0, 1, 2, '', 0, '0000-00-00', 'Active', 2),
(8, 0, 1, 2, '', 0, '0000-00-00', 'Active', 2);

-- 
-- Dumping data for table payment
--
-- Table hospital.payment does not contain any data (it is empty)

-- 
-- Dumping data for table patient
--
INSERT INTO patient VALUES
(2, 'Marianne Joyce Alejaga', '2022-11-16', '05:51:47', 'Bgry. Balucuan Dao, Capiz', '09101159346', 'capiz', '', '3', '123456789', '', 'Female', '2009-01-06', 'Active'),
(3, 'TEST PATIENT', '2023-05-30', '17:32:29', 'MANILA', '639958242310', 'ROXAS CITY', '5800', 'patient1', '123', 'A+', 'MALE', '1998-10-12', 'Active'),
(4, 'asdasdasdasdas', '2023-05-30', '19:16:25', '12412421412', '21412421', 'asdasdasdas', NULL, '224242', '12345678', NULL, 'Male', '2023-06-03', 'Active');

-- 
-- Dumping data for table orders
--
-- Table hospital.orders does not contain any data (it is empty)

-- 
-- Dumping data for table medicine
--
INSERT INTO medicine VALUES
(1, 'Paracetamol', 3.00, 'For fever per day 1 pc', 'Active'),
(2, 'Mefenamic Acid', 5.00, 'Treat mild to moderate pain', 'Active');

-- 
-- Dumping data for table doctor_timings
--
-- Table hospital.doctor_timings does not contain any data (it is empty)

-- 
-- Dumping data for table doctor
--
INSERT INTO doctor VALUES
(1, 'Jeffrey De Tomas', '2125798361', 1, 'tomas', '123456789', 'Active', 'MBBS', 7.0, 800.00),
(2, 'Aikee Marvin Lacdao', '09101159346', 2, 'lacdao', '123456789', 'Active', 'BSME', 7.0, 50.00);

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
(1, 'Internal Medicine', 'Internal Medicine', 'Active'),
(2, 'Pharmacy', 'Reviewing Medications', 'Active'),
(3, 'Radiology', 'Diagnostic Radiology', 'Active');

-- 
-- Dumping data for table billing_records
--
INSERT INTO billing_records VALUES
(4, 2, 1, 'Consultancy Charge', 800.00, '2022-11-16', 'Active'),
(5, 2, 20, 'Treatment', 300.00, '2022-11-16', 'Active'),
(6, 2, 2, 'Prescription Charge', 15.00, '2022-11-16', 'Active'),
(7, 2, 3, 'Prescription Charge', 3.00, '2022-11-16', 'Active'),
(8, 2, 4, 'Prescription Charge', 0.00, '2022-11-17', 'Active'),
(9, 2, 5, 'Prescription Charge', 0.00, '2022-12-05', 'Active'),
(10, 2, 6, 'Prescription Charge', 3.00, '2022-12-09', 'Active'),
(11, 2, 7, 'Prescription Charge', 5.00, '2022-12-09', 'Active'),
(12, 2, 8, 'Prescription Charge', 0.00, '2023-01-16', 'Active');

-- 
-- Dumping data for table billing
--
INSERT INTO billing VALUES
(1, 1, 1, '2022-11-15', '14:56:31', 0.00, 0.00, '', '00:00:00', '0000-00-00'),
(2, 2, 2, '2022-11-16', '05:53:07', 0.00, 0.00, '', '00:00:00', '0000-00-00');

-- 
-- Dumping data for table appointment
--
INSERT INTO appointment VALUES
(1, '', 1, 0, 1, '2022-11-15', '21:50:00', 1, 'Approved', 'fever'),
(2, '', 2, 0, 1, '2022-11-16', '12:51:00', 1, 'Approved', 'fever'),
(3, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, NULL, 3, NULL, 1, NULL, NULL, 1, 'Active', 'asfasfas'),
(7, NULL, 3, NULL, 1, '2023-05-30', '18:32:39', 1, 'Active', 'test'),
(8, NULL, 3, NULL, 1, '1970-01-01', '00:00:00', 1, 'Active', 'atestas'),
(9, NULL, 3, NULL, 1, '1970-01-01', '00:00:00', 1, 'Active', 'testas'),
(10, NULL, 3, NULL, 1, '2023-05-30', '18:39:49', 1, 'Active', 'test'),
(11, 'ONLINE', 0, NULL, 1, '2023-06-01', '03:06:00', 1, 'Pending', 'test'),
(12, 'ONLINE', 224242, NULL, 1, '2023-06-02', '03:16:00', 1, 'Pending', 'test'),
(13, 'ONLINE', 224242, NULL, 2, '2023-06-01', '03:17:00', 2, 'Pending', 'test');

-- 
-- Dumping data for table admin
--
INSERT INTO admin VALUES
(1, 'ITSC', 'admin', '123456789', 'Active', '');

-- 
-- Dumping data for table add_opdpatients
--
-- Table hospital.add_opdpatients does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;